id: dsq-747521339
date: 2007-07-01T23:36:56.0000000-07:00
name: Chris May
avatar: https://disqus.com/api/users/avatars/Chris May.jpg
message: <p>Is there any fix for this to get it working on XP?</p>
